# Generated by Django 5.0.6 on 2024-08-18 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="reactions",
        ),
        migrations.RemoveField(
            model_name="post",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="post",
            name="reactions",
        ),
        migrations.RemoveField(
            model_name="post",
            name="shares",
        ),
        migrations.AddField(
            model_name="comment",
            name="content_type",
            field=models.ForeignKey(
                default=23,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
