# Generated by Django 5.0.6 on 2024-08-18 16:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_remove_comment_reactions_remove_post_comments_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
    ]
