# Generated by Django 5.0.6 on 2024-08-18 15:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="education",
            name="shares",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="shares",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="notifications",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="notifications",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="shares",
        ),
    ]
