# Generated by Django 5.0.6 on 2024-08-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_initial"),
        ("profiles", "0002_remove_education_shares_remove_experience_shares_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobapplication",
            name="shares",
        ),
        migrations.RemoveField(
            model_name="joblisting",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="joblisting",
            name="shares",
        ),
        migrations.RemoveField(
            model_name="jobnotification",
            name="shares",
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="skills_required",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                related_name="required_skills_jobs",
                to="profiles.skill",
            ),
        ),
    ]
