# Generated by Django 5.0.6 on 2024-08-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_jobapplication_shares_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='program_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='program_type',
            field=models.CharField(choices=[('internship', 'Internship'), ('fellowship', 'Fellowship'), ('job', 'Job')], default='job', max_length=50),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('education', 'Education'), ('contract', 'Contract'), ('internship', 'Internship'), ('fellowship', 'Fellowship')], max_length=50),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('entry_level', 'Entry Level'), ('mid_level', 'Mid Level'), ('senior_level', 'Senior Level'), ('student_level', 'Student Level')], max_length=50),
        ),
    ]
