# settings/notifications_settings.py

from config.constances import NOTIFICATION_FREQUENCY, DO_NOT_DISTURB

NOTIFICATION_FREQUENCY_SETTINGS = {
    'IMMEDIATE': NOTIFICATION_FREQUENCY['IMMEDIATE'],
    'HOURLY_DIGEST': NOTIFICATION_FREQUENCY['HOURLY_DIGEST'],
    'DAILY_DIGEST': NOTIFICATION_FREQUENCY['DAILY_DIGEST'],
    # Add more frequency options as needed
}

DO_NOT_DISTURB_SETTINGS = {
    'START_TIME': DO_NOT_DISTURB['START_TIME'],
    'END_TIME': DO_NOT_DISTURB['END_TIME'],
}
