# Generated by Django 5.0.6 on 2024-07-23 21:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_attachment_choice_course_duration_course_image_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attachment",
        ),
    ]
