# Generated by Django 5.0.6 on 2024-08-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_delete_attachment'),
        ('courses', '0007_alter_question_correct_choice'),
    ]

    operations = [
    ]
