from django.urls import path
from . import views

urlpatterns = [
    path('', views.get_all_profiles, name='get_all_profiles'),
    path('<int:profile_id>/', views.get_specific_profile, name='get_specific_profile'),
    path('create/', views.create_profile, name='create_profile'),
    path('update/<int:profile_id>/', views.update_profile, name='update_profile'),
    path('delete/<int:profile_id>/', views.delete_profile, name='delete_profile'),
    path('delete/all/', views.delete_all_profiles, name='delete_all_profiles'),
    path('followers/<int:profile_id>/', views.get_followers, name='get_followers'),
    path('experiences/<int:profile_id>/', views.get_experiences, name='get_experiences'),
    path('experiences/<int:profile_id>/<int:experience_id>/', views.get_experience, name='get_experience'),
    path('experiences/update/<int:profile_id>/<int:experience_id>/', views.update_experience, name='update_experience'),
    path('experiences/delete/<int:profile_id>/<int:experience_id>/', views.delete_experience, name='delete_experience'),
    path('experiences/delete/all/<int:profile_id>/', views.delete_all_experiences, name='delete_all_experiences'),
    path('educations/<int:profile_id>/', views.get_educations, name='get_educations'),
    path('educations/<int:profile_id>/<int:education_id>/', views.get_education, name='get_education'),
    path('educations/update/<int:profile_id>/<int:education_id>/', views.update_education, name='update_education'),
    path('educations/delete/<int:profile_id>/<int:education_id>/', views.delete_education, name='delete_education'),
    path('educations/delete/all/<int:profile_id>/', views.delete_all_educations, name='delete_all_educations'),
    path('skills/<int:profile_id>/', views.get_skills, name='get_skills'),
    path('skills/<int:profile_id>/<int:skill_id>/', views.get_skill, name='get_skill'),
    path('skills/update/<int:profile_id>/<int:skill_id>/', views.update_skill, name='update_skill'),
    path('skills/delete/<int:profile_id>/<int:skill_id>/', views.delete_skill, name='delete_skill'),
    path('skills/delete/all/<int:profile_id>/', views.delete_all_skills, name='delete_all_skills'),
    path('achievements/<int:profile_id>/', views.get_achievements, name='get_achievements'),
    path('achievements/<int:profile_id>/<int:achievement_id>/', views.get_achievement, name='get_achievement'),
    path('achievements/update/<int:profile_id>/<int:achievement_id>/', views.pdate_achievement, name='update_achievement'),
    path('achievements/delete/<int:profile_id>/<int:achievement_id>/', views.delete_achievement, name='delete_achievement'),
    path('achievements/delete/all/<int:profile_id>/', views.delete_all_achievements, name='delete_all_achievements'),
    path('portfolios/<int:profile_id>/', views.get_portfolios, name='get_portfolios'),
    path('portfolios/<int:profile_id>/<int:portfolio_id>/', views.get_portfolio, name='get_portfolio'),
    path('portfolios/update/<int:profile_id>/<int:portfolio_id>/', views.update_portfolio, name='update_portfolio'),
    path('portfolios/delete/<int:profile_id>/<int:portfolio_id>/', views.delete_portfolio, name='delete_portfolio'),
    path('portfolios/delete/all/<int:profile_id>/', views.delete_all_portfolios, name='delete_all_portfolios'),
    path('report/<int:profile_id>/', views.get_profile_report, name='get_profile_report'),
]