# Generated by Django 5.0.6 on 2024-08-18 15:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0004_reaction_content_type_reaction_object_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reaction",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="group",
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="job_post",
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="message",
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="post",
        ),
    ]
