# Generated by Django 5.0.6 on 2024-08-18 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0005_remove_reaction_comment_remove_reaction_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reaction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
