# Generated by Django 5.0.6 on 2024-08-19 00:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0006_reaction_created_at"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reaction",
            unique_together={("user", "content_type", "object_id")},
        ),
    ]
