# Generated by Django 5.0.6 on 2024-08-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='services',
            field=models.TextField(blank=True),
        ),
    ]
