# Generated by Django 5.0.6 on 2024-08-17 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='revoked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='LinkedInBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_image', models.ImageField(blank=True, upload_to='linkedin_badges/')),
                ('badge_url', models.URLField(blank=True)),
                ('share_on_linkedin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_badge', to='certifications.certification')),
            ],
        ),
    ]
