# Generated by Django 5.0.6 on 2024-08-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0005_certification_revoked_linkedinbadge'),
        ('events', '0004_remove_event_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='related_events',
            field=models.ManyToManyField(blank=True, related_name='event_certifications', to='events.event'),
        ),
    ]
