# Generated by Django 5.0.6 on 2024-08-15 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_initial'),
        ('groups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('is_achieved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='permissions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='categories',
            field=models.ManyToManyField(related_name='group_categories', to='activity.category'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('project_manager', 'Project Manager')], default='member', max_length=20),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_announcements', to='groups.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='announcements',
            field=models.ManyToManyField(blank=True, related_name='groups_announcements', to='groups.announcement'),
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_discussions', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_discussions', to='groups.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='discussions',
            field=models.ManyToManyField(blank=True, related_name='groups_discussions', to='groups.discussion'),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('meeting_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='meeting_participants', to=settings.AUTH_USER_MODEL)),
                ('related_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_meetings', to='groups.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='meetings',
            field=models.ManyToManyField(blank=True, related_name='groups_meetings', to='groups.meeting'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_messages', to=settings.AUTH_USER_MODEL)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_messages', to='groups.discussion')),
            ],
        ),
        migrations.AddField(
            model_name='discussion',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='discussion_messages', to='groups.message'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='not_started', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='project_members', to=settings.AUTH_USER_MODEL)),
                ('milestones', models.ManyToManyField(blank=True, related_name='related_project_milestones', to='groups.milestone')),
            ],
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones_in_project', to='groups.project'),
        ),
        migrations.AddField(
            model_name='group',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='groups_projects', to='groups.project'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_in_project', to='groups.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='related_project_tasks', to='groups.task'),
        ),
    ]
