# Generated by Django 5.0.6 on 2024-08-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0005_remove_reaction_comment_remove_reaction_group_and_more"),
        ("groups", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="shares",
        ),
        migrations.AlterField(
            model_name="group",
            name="categories",
            field=models.ManyToManyField(
                related_name="groups_categories", to="activity.category"
            ),
        ),
    ]
