# Generated by Django 5.0.6 on 2024-08-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_milestone_groupmembership_permissions_and_more'),
        ('groups', '0003_remove_group_shares_alter_group_categories'),
    ]

    operations = [
    ]
