# Generated by Django 5.0.6 on 2024-06-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notificationtype_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, max_length=255, null=True),
        ),
    ]
