# Generated by Django 5.0.6 on 2024-07-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0005_alter_notification_object_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsettings",
            name="channel_preferences",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="notification",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "Low"), (2, "Medium"), (3, "High"), (4, "Critical")],
                default=1,
            ),
        ),
    ]
