# Generated by Django 5.0.6 on 2024-07-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0006_notificationsettings_channel_preferences_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
