# Generated by Django 5.0.6 on 2024-07-24 18:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0008_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="notificationengagement",
            name="viewed_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="timestamp",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
    ]
