from django.urls import path
from activity import views

urlpatterns = [
    path('user-statistics/', views.get_user_statistics, name='get_user_statistics'),
    path('user-statistics/<int:user_statistic_id>/', views.get_specific_user_statistic, name='get_specific_user_statistic'),
    path('user-statistics/create/', views.create_user_statistic, name='create_user_statistic'),
    path('user-statistics/update/<int:user_statistic_id>/', views.update_user_statistic, name='update_user_statistic'),
    path('user-statistics/delete/<int:user_statistic_id>/', views.delete_user_statistic, name='delete_user_statistic'),
    path('user-statistics/delete/all/', views.delete_all_user_statistics, name='delete_all_user_statistics'),
    path('marketing-campaigns/', views.get_marketing_campaigns, name='get_marketing_campaigns'),
    path('marketing-campaigns/<int:marketing_campaign_id>/', views.get_specific_marketing_campaign, name='get_specific_marketing_campaign'),
    path('marketing-campaigns/create/', views.create_marketing_campaign, name='create_marketing_campaign'),
    path('marketing-campaigns/update/<int:marketing_campaign_id>/', views.update_marketing_campaign, name='update_marketing_campaign'),
    path('marketing-campaigns/delete/<int:marketing_campaign_id>/', views.delete_marketing_campaign, name='delete_marketing_campaign'),
    path('marketing-campaigns/delete/all/', views.delete_all_marketing_campaigns, name='delete_all_marketing_campaigns'),
    path('threads/', views.get_threads, name='get_threads'),
    path('threads/<int:thread_id>/', views.get_specific_thread, name='get_specific_thread'),
    path('threads/create/', views.create_thread, name='create_thread'),
    path('threads/update/<int:thread_id>/', views.update_thread, name='update_thread'),
    path('threads/delete/<int:thread_id>/', views.delete_thread, name='delete_thread'),
    path('threads/delete/all/', views.delete_all_threads, name='delete_all_threads'),
    path('reactions/', views.get_reactions, name='get_reactions'),
    path('reactions/<int:reaction_id>/', views.get_specific_reaction, name='get_specific_reaction'),
    path('reactions/create/', views.create_reaction, name='create_reaction'),
    path('reactions/update/<int:reaction_id>/', views.update_reaction, name='update_reaction'),
    path('reactions/delete/<int:reaction_id>/', views.delete_reaction, name='delete_reaction'),
    path('reactions/delete/all/', views.delete_all_reactions, name='delete_all_reactions'),
    path('shares/', views.get_shares, name='get_shares'),
    path('shares/<int:share_id>/', views.get_specific_share, name='get_specific_share'),
    path('shares/create/', views.create_share, name='create_share'),
    path('shares/update/<int:share_id>/', views.update_share, name='update_share'),
    path('shares/delete/<int:share_id>/', views.delete_share, name='delete_share'),
    path('shares/delete/all/', views.delete_all_shares, name='delete_all_shares'),
]